### ISSUE TITLE
Doesn't work properly

### ISSUE THREAD

**Issue by khokonm** [DavidGarciaCat/php-nudity-image-blocker#1]
Hi, 
I'm really excited about your project. But it's not working properly. Sometimes, it gives normal images a score above 60, and most of the time, the score for an adult image is below 60.
I appreciate your hard work.
Thanks
Khokon

**Comment by DavidGarciaCat** [comment]
Hello @khokonm 

Thank you for your kind words. However, as you can read in the [README](https://github.com/DavidGarciaCat/php-nudity-image-detector#php-nudity-and-porn-image-detector) file, this is not my work, and I don't plan to take any credit for it

```
PHP code by Bakr Alsharif from Egypt:
http://www.9lessons.info/2014/01/block-uploads-of-adult-or-nude-images.html
```

Either for good or for bad, the "nude detector" logic works trying to "match skin colour", so if you use pictures where there are tons of blue, red, green... those will get flagged as "non-nudity" images because people's skin doesn't have any of those colours. On the other hand, any image with more "skin-like colour" might return a false positive even if that's not nudity.

This code must be used as an initial filter but a manual review is always required to ensure no one submits and uploads to your projects any illegal content.

Warm regards,

**Comment by DavidGarciaCat** [comment]
By the way, you can try this other project too

https://github.com/DavidGarciaCat/php-nudity-detector

Maybe it gives you better results
